"""GREAT SDD Kit — Signatures (Input/Output Contracts)."""
from great_sdd.signatures.pre_estimation import (
    VALIDATE_LINE_SELECTION,
    CHECK_ROLE_PERMISSION,
    VALIDATE_STATUS_TRANSITION,
    SELECT_INDUCTOR_CRAN,
    GENERATE_ESTIMATE,
    VALIDATE_BEFORE_SAVE,
    DISTRIBUTE_BY_MONTH,
    GENERATE_PRE_SAVE_SUMMARY,
)
from great_sdd.signatures.estimation_review import (
    CHECK_ESTIMATION_REVIEW_PERMISSION,
    DERIVE_APPROVAL_COLUMNS,
    CHECK_SEND_ELIGIBILITY,
    PROCESS_HVT_CALLBACK_SIG,
    GENERATE_HVT_PAYLOAD,
    EXPORT_CSV,
)
from great_sdd.signatures.allocation import (
    CHECK_ALLOCATION_PERMISSION,
    FILTER_APPROVED_JUS,
    MATCH_ALLOCATION_RULES,
    ROUTE_HPROJECT_HNP,
    CALCULATE_KE,
    HANDLE_TC_POPUP,
    HANDLE_SPLIT,
    BULK_ASSIGN,
    VALIDATE_ALLOCATION_SAVE,
    CHECK_DROPDOWN_DIVERSITY,
)
from great_sdd.signatures.final_review import (
    CHECK_FINAL_REVIEW_PERMISSION,
    FILTER_FINAL_REVIEW_JUS,
    AGGREGATE_FINAL_REVIEW,
    EXPORT_FINAL_REVIEW_CSV,
    SEND_STAGE3,
    CALCULATE_SUBTOTALS,
)

__all__ = [
    # Pre-Estimation
    "VALIDATE_LINE_SELECTION",
    "CHECK_ROLE_PERMISSION",
    "VALIDATE_STATUS_TRANSITION",
    "SELECT_INDUCTOR_CRAN",
    "GENERATE_ESTIMATE",
    "VALIDATE_BEFORE_SAVE",
    "DISTRIBUTE_BY_MONTH",
    "GENERATE_PRE_SAVE_SUMMARY",
    # Estimation Review
    "CHECK_ESTIMATION_REVIEW_PERMISSION",
    "DERIVE_APPROVAL_COLUMNS",
    "CHECK_SEND_ELIGIBILITY",
    "PROCESS_HVT_CALLBACK_SIG",
    "GENERATE_HVT_PAYLOAD",
    "EXPORT_CSV",
    # Allocation
    "CHECK_ALLOCATION_PERMISSION",
    "FILTER_APPROVED_JUS",
    "MATCH_ALLOCATION_RULES",
    "ROUTE_HPROJECT_HNP",
    "CALCULATE_KE",
    "HANDLE_TC_POPUP",
    "HANDLE_SPLIT",
    "BULK_ASSIGN",
    "VALIDATE_ALLOCATION_SAVE",
    "CHECK_DROPDOWN_DIVERSITY",
    # Final Review
    "CHECK_FINAL_REVIEW_PERMISSION",
    "FILTER_FINAL_REVIEW_JUS",
    "AGGREGATE_FINAL_REVIEW",
    "EXPORT_FINAL_REVIEW_CSV",
    "SEND_STAGE3",
    "CALCULATE_SUBTOTALS",
]
